@startuml
Participant Client
Participant Customer
Participant Account

Client -> Customer: Create Customer
Customer -> Client: Return Customer ID
Client -> Account: Create Account with Given Customer Id
Account -> Client : Return Account ID

@enduml